name: Build and Release Touhou Cursors
on:
  push:
    branches: [main]
    paths:
      - "cursor_data.json"
      - "CursorConverter/**"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pillow cursorgen

      - name: Process Touhou Cursors
        run: |
          mkdir -p dist
          python .github/scripts/process_cursors.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: touhou-cursors-${{ github.run_number }}
          name: Touhou Cursors Release ${{ github.run_number }}
          body: |
            Automated release of Touhou cursor sets (1-10 and 11-20)

            This release includes processed cursor sets for all characters from:
            - 東方マウスカーソル　1～10 (Touhou Mouse Cursors 1-10)
            - 東方マウスカーソル　11～20 (Touhou Mouse Cursors 11-20)
          files: |
            dist/*.zip
          draft: false
          prerelease: false
